#!/bin/sh

echo 'Content-Type: text/plain'
echo

cd "$1"

siteName="$2"
spaceName="$3"
factoryName="$4"
ip="$5"
mac="$6"
subnet="$7"
netmask="$8"
router="$9"
isolinuxcfg="${10}"

for i in ${11} ${12} ${13} ${14}
do
  nameservers="$nameservers nameserver=$i"
done

cp -a /var/lib/viab/boot-CentOS7 .

cd boot-CentOS7

sed \
 -e "s/##FACTORYNAME##/$factoryName/"\
 -e "s/##SITENAME##/$siteName/"\
 -e "s/##SPACENAME##/$spaceName/" \
 -e "s/##IFNAME##/viab0:$mac/" \
 -e "s/##IP##/$ip::$router:$netmask:$factoryName:viab0:none/" \
 -e "s/##NAMESERVERS##/$nameservers/" \
 "$isolinuxcfg" > isolinux/isolinux.cfg

genisoimage -U -r -v -T -J -joliet-long \
 -V      "ViaB-CentOS-7" \
 -volset "ViaB-CentOS-7" \
 -A      "ViaB-CentOS-7" \
 -b isolinux/isolinux.bin \
 -c isolinux/boot.cat \
 -no-emul-boot -boot-load-size 4 -boot-info-table \
 -eltorito-alt-boot \
 -e images/efiboot.img \
 -no-emul-boot -o ../boot.iso .

isohybrid ../boot.iso

cat ../boot.iso

