#!/bin/sh

echo 'Content-Type: text/plain'
echo

cd "$1"

siteName="$2"
spaceName="$3"
factoryName="$4"
ip="$5"
subnet="$6"
netmask="$7"
router="$8"
nameservers="$9 $10 $11 $12"

cp -a /var/lib/viab/boot-CentOS7 .

cd boot-CentOS7

sed -i \
 -e "s/##SITENAME##/$siteName/" \
 -e "s/##SPACENAME##/$spaceName/" \
 -e "s/##IP##/$ip::$router:$netmask:$factory::none/" \
 -e "s/##NAMESERVERS##/$nameservers/" \
 isolinux/isolinux.cfg

genisoimage -U -r -v -T -J -joliet-long \
 -V      "ViaB CentOS 7" \
 -volset "ViaB CentOS 7" \
 -A      "ViaB CentOS 7" \
 -b isolinux/isolinux.bin \
 -c isolinux/boot.cat \
 -no-emul-boot -boot-load-size 4 -boot-info-table \
 -eltorito-alt-boot \
 -e images/efiboot.img \
 -no-emul-boot -o ../boot.iso .

isohybrid ../boot.iso

cat ../boot.iso

