#!/bin/sh

if [ ! -r /etc/viabkeys/viab-conf-passphrase ] ; then
  echo 'You need to put your p12 files passphrase in /etc/viab-conf-passphrase !'
  exit 1
fi

chmod go-r /etc/viabkeys/viab-conf-passphrase

for i in /var/lib/vac/machinetypes/*
do
 cd $i
 if [ -s hostcertkey.p12 ] ; then
  echo "Create hostcert.pem/hostkey.pem from $i/hostcertkey.p12"
  openssl pkcs12 -in hostcertkey.p12 -passin file:/etc/viabkeys/viab-conf-passphrase -out hostkey.pem  -nodes -nocerts
  openssl pkcs12 -in hostcertkey.p12 -passin file:/etc/viabkeys/viab-conf-passphrase -out hostcert.pem -nokeys -clcerts
 else
  echo "Empty $i/hostcertkey.p12"
  echo > hostcert.pem
  echo > hostkey.pem
 fi
 chmod ugo-w,go-r hostkey.pem 
done

if [ -r /etc/viab/vac-apel-certkey.p12 ] ; then
 echo "Create /etc/grid-security/vac-apel-key.pem"
 chmod u+w /etc/grid-security/vac-apel-key.pem
 openssl pkcs12 -in /etc/viab/vac-apel-certkey.p12 -passin file:/etc/viabkeys/viab-conf-passphrase -out /etc/grid-security/vac-apel-key.pem  -nodes -nocerts
 openssl pkcs12 -in /etc/viab/vac-apel-certkey.p12 -passin file:/etc/viabkeys/viab-conf-passphrase -out /etc/grid-security/vac-apel-cert.pem -nokeys -clcerts
 chmod ugo-w,go-r /etc/grid-security/vac-apel-key.pem
fi
