#!/bin/sh

tempDir="$1"
siteName="$2"
spaceName="$3"
factoryName="$4"
ip="$5"
subnet="$6"
netmask="$7"
router="$8"
nanmeservers="$9 $10 $11 $12"

genisoimage -U -r -v -T -J -joliet-long \
 -V "ViaB 7 CentOS 7" \
 -volset "ViaB 7 CentOS 7" \
 -A ViaB 7 CentOS 7" \
 -b isolinux/isolinux.bin -c isolinux/boot.cat \
 -no-emul-boot -boot-load-size 4 -boot-info-table \
 -eltorito-alt-boot -e images/efiboot.img \
 -no-emul-boot -o ../NEWISO.iso .

isohybrid ../NEWISO.iso
