#!/bin/sh
#
# This is an idempotent script which is run after a new version of the 
# viab-conf RPM is installed and at boot time. During testing, it can 
# be run at any time on a Vac-in-a-Box machine to apply changes to the 
# configuration.
#

# First remove the existing ViaB ssh etc, catch-all REJECT iptables rules, default ssh rule, VM SMTP block
/sbin/iptables-save | /bin/egrep -v 'ViaB [[:alnum:]]* access' | /sbin/iptables-restore

#echo 'Try to delete some old iptable rules'
/sbin/iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited
/sbin/iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 2>/dev/null
/sbin/iptables -D FORWARD -p tcp --dport 25 -j DROP

# Now (re)add the current ssh iptables rules
cat /etc/viab/sshrules | (

while read ip netmask
do
 /sbin/iptables -t filter -A INPUT -s $ip/$netmask -p tcp -m state --state NEW -m tcp --dport 22 -m comment --comment "ViaB ssh access" -j ACCEPT
done

)

cat /etc/viab/subnets | (

while read subnet netmask router nameservers ntpservers
do
 echo "subnet $subnet netmask $netmask { option routers $router; option domain-name-servers $nameservers; option ntp-servers $ntpservers; }" >>/etc/dhcp/dhcpd.conf.tmp
 /sbin/iptables -A INPUT -s $subnet/$netmask -p udp -m state --state NEW -m udp --dport 67 -m comment --comment "ViaB boot access" -j ACCEPT 
 /sbin/iptables -A INPUT -s $subnet/$netmask -p udp -m state --state NEW -m udp --dport 68 -m comment --comment "ViaB boot access" -j ACCEPT 
 /sbin/iptables -A INPUT -s $subnet/$netmask -p udp -m state --state NEW -m udp --dport 69 -m comment --comment "ViaB boot access" -j ACCEPT 
 /sbin/iptables -A INPUT -s $subnet/$netmask -p udp -m state --state NEW -m udp --dport 995 -m comment --comment "ViaB VacQuery access" -j ACCEPT 
 /sbin/iptables -A INPUT -s $subnet/$netmask -p tcp -m state --state NEW -m tcp --dport 3128 -m comment --comment "ViaB Squid access" -j ACCEPT 
 /sbin/iptables -A INPUT -s $subnet/$netmask -p tcp -m state --state NEW -m tcp --dport 3130 -m comment --comment "ViaB Squid access" -j ACCEPT
done

)

# Re-add the HTTP metadata/mjf rule
/sbin/iptables -A INPUT -i virbr1 -p tcp -m tcp --dport 80 -m comment --comment "ViaB HTTP access" -j ACCEPT

# Re-add the Squid rule
/sbin/iptables -A INPUT -i virbr1 -p tcp -m tcp --dport 3128 -m comment --comment "ViaB Squid access" -j ACCEPT

# Re-add the catch-all reject rule
/sbin/iptables -A INPUT -j REJECT --reject-with icmp-host-prohibited

# Re-add the outgoing SMTP block for the VMs
/sbin/iptables -I FORWARD -p tcp --dport 25 -j DROP

# Right at the end, we save iptables in case the machine is rebooted
# directly from the hard drive rather than with a reinstall
/sbin/service iptables save

